version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=conduit-db
      - POSTGRES_PASSWORD=conduit-db
      - POSTGRES_DB=conduit-api-db

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
volumes:
  db: